# NOTE: restart server for changes to take effect!
env: development
# env: production

# ********** SERVER **********
server: 
  http:
    protocol: http
    hostname: localhost
    port: 3000
  ws:
    port: 3000
    cors: 
      origens: '*'

# ********** SECURITY **********
token:
  access: 
    expiry: '30m'
    secret: my-secret-access-token
  refresh:
    expiry: '30d'

# ********** MAIL **********
email:
  service: gmail
  auth:
    user: 'aox.mailer@gmail.com'
    pass: Iamdavid7D

# ********** DB **********
database:
    client: postgresql
    connection:
        database: account-manager
        host: '192.168.50.251'
        port: 3000
        user: admin
        password: admin
    migrations:
        tableName: knex_migrations
        directory: ./db/migrations
    seeds:
      directory: ./db/seeds
    pool:
        min: 2

# ********** CLIENT **********
client: 
  http:
    protocol: http
    hostname: localhost
    port: 8080
  routes:
    password_recovery: '/recover-password'
    email_verification: '/verify-email'
    device_verification: '/verify-device'
    device_make_primary: '/make-primary-device'
